# Generated by Django 5.2.7 on 2026-06-19 02:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_user_csv_meteo_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPerformanceRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_oper', models.CharField(blank=True, db_index=True, default='ALL', max_length=30)),
                ('source_meteo', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensal'), ('annual', 'Anual')], db_index=True, default='monthly', max_length=12)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('ts_start_utc', models.DateTimeField(db_index=True)),
                ('ts_end_utc', models.DateTimeField(db_index=True)),
                ('performance_ratio', models.FloatField(blank=True, help_text='Performance ratio corrigido por temperatura.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('raw_performance_ratio', models.FloatField(blank=True, help_text='Performance ratio sem correcao termica.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('energy_kwh', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('irradiation_kwh_m2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('denominator_kwh', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pnom_kwp', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('t_array_weighted_c', models.FloatField(blank=True, null=True)),
                ('mu_pmpp_per_c', models.FloatField(blank=True, null=True)),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('valid_samples_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_ratios', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Performance ratio corrigido por temperatura',
                'verbose_name_plural': 'Performance ratios corrigidos por temperatura',
                'ordering': ['plant_id', 'period', 'period_start'],
                'indexes': [models.Index(fields=['plant', 'period', 'period_start'], name='idx_prtemp_plant_period'), models.Index(fields=['plant', 'source_meteo', 'period_start'], name='idx_prtemp_plant_meteo')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'source_oper', 'source_meteo', 'period', 'period_start'), name='uniq_prtemp_plant_sources_period')],
            },
        ),
    ]
