# Generated by Django 5.2.7 on 2026-06-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_plantperformanceratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='growatt_datalogger_sn',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='growatt_device_sn',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='growatt_device_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='growatt_devices_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='growatt_plant_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='growatt_plants_cache',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
